services:
  bdd:
    container_name: reims_mariadb
    image: mariadb:latest
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: TOOR
      MARIADB_DATABASE: reims
      MARIADB_USER: roger
      MARIADB_PASSWORD: regor
    profiles: [prod, dev]

  api:
    container_name: reims_api
    image: senseo/reims23:main
    restart: always
    depends_on:
      - bdd
    ports:
      - 23000:23000
    environment:
      BDD_HOST: bdd
    profiles: [prod, dev]

  adminer:
    container_name: reims_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    profiles: [dev]
