name: Deploy Canary Mode

on:
    workflow_call

jobs:
    deploy:
        runs-on: self-hosted

        env:
            SERVER_PORT: 23000
            BDD_HOST: 127.0.0.1
            BDD_PORT: 3306
            BDD_NAME: reims
            BDD_USER: roger
            BDD_PASS: regor
            BCRYPT_SALT_ROUND: 10

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 18.x

            
            - name: install Dependencies
              run: npm i --omit=dev

            - name: Start API
              run: npm run start