name: Deploy on prod

on:
    workflow_call

jobs:
    push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Docker Login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_LOGIN }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract Metada
              id: meta
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                images: senseo/reims23

            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.label }}

    compose:
        needs: [push]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Compose file send
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.PROD_HOST }}
                port: ${{ secrets.PROD_PORT }}
                username: ${{ secrets.PROD_USERNAME }}
                password: ${{ secrets.PROD_PASSWORD }}

                source: "./docker-compose.yml"
                target: "."

    pull:
        needs: [push,compose]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Server update
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.PROD_HOST }}
                port: ${{ secrets.PROD_PORT }}
                username: ${{ secrets.PROD_USERNAME }}
                password: ${{ secrets.PROD_PASSWORD }}
                
                script: |
                  docker pull senseo/reims:main
                  docker-compose --profile=prod up -d
